### ISSUE TITLE
GNU-specific compiler flags

### ISSUE THREAD

**Issue by samhatfield** [ecmwf/metkit#1]
In [`metkit/cmake/compiler_warnings.cmake`](https://github.com/ecmwf/metkit/blob/master/cmake/compiler_warnings.cmake) a few options are added specifically for the GNU compiler. Should the `-Wall` and `-Wextra` flags also be under this if statement? I am trying to compile Metkit with the Fujitsu compiler and it doesn't recognise these flags, so I have to manually remove them from this `CMakeLists.txt`. My understanding is that these are GNU-specific and some other, but not all, compilers recognise them.

**Comment by wdeconinck** [comment]
It should have the NO_FAIL argument as well, so that it ignores the flag if it is not recognised. This is also what is done in eckit:
https://github.com/ecmwf/eckit/blob/develop/cmake/compiler_warnings.cmake#L8

**Comment by tlmquintino** [comment]
Yes that is correct.

**Comment by samhatfield** [comment]
Thanks!

**Comment by dtip** [comment]
Closing this because it seems fixed.
